Cysharp/ConsoleAppFramework

src/MicroBatchFramework/BatchEngineService.cs, src/MicroBatchFramework/IBatchInterceptor.cs
In `OnBatchEngineBeginAsync` method, we want to use a logger and `IServiceProvider`.
For example, Initialize app or other dependent libraries, they need a logger or IServiceProvider.
=> feat: Pass logger and ServiceProvider to BatchInterceptor

sandbox/SingleContainedAppWithConfig/Program.cs
EnvironmentName should be case-sensitive. Some file systems are case-insensitive.
The batch app may fail to read a appsettings.Development.json.
```
C:\> dotnet run
info: MicroBatchFramework.BatchEngine[0]
GlobalValue: GLOBAL VALUE!!!!, EnvValue: ENV VALUE!!!!
```
```
$ dotnet run
info: MicroBatchFramework.BatchEngine[0]
GlobalValue: GLOBAL VALUE!!!!, EnvValue: ENV VALUE!!!!(PRODUCTION)
```
=> fix: EnvironmentName should be case-sensitive

sandbox/SingleContainedAppWithConfig/Program.cs, src/MicroBatchFramework/Configuration/MicroBatchHost.cs, src/MicroBatchFramework/MicroBatchFramework.csproj, src/MicroBatchFramework/MicroBatchHost.cs
Offer default builder as asp.net core webhost does.
This will make user don't need to think about configuration.
Should Replace other samples to use MicroBatchHost?
=> feat: Add MicroBatchHost as a Default Builder

src/MicroBatchFramework/BatchEngine.cs
If a batch method doesn't have any `Option` attribute, `BatchEngine` can't match any command argument.
It seems to works well when running MicroBatchFramework 0.3.1 or prior.
```
> cd sandbox\MultiContainedApp
> dotnet run Foo.Echo -msg hoge
Fail to match method parameter on Foo.Echo. args: Foo.Echo -msg hoge
System.NullReferenceException: Object reference not set to an instance of an object.
at MicroBatchFramework.BatchEngine.TryGetInvokeArguments(ParameterInfo[] parameters, String[] args, Int32 argsOffset, Object[]& invokeArgs, String& errorMessage) in C:\Users\Tomoyo\Source\Repos\MicroBatchFramework\src\MicroBatchFramework\BatchEngine.cs:line 179
at MicroBatchFramework.BatchEngine.RunCore(BatchContext ctx, Type type, MethodInfo methodInfo, String[] args, Int32 argsOffset) in …
```
=> fix: Can't match implicit command argument.

sandbox/MultiContainedApp/Program.cs, src/MicroBatchFramework/BatchEngineHostBuilderExtensions.cs, src/MicroBatchFramework/BatchHost.cs
`BatchHost.CreateDefaultBuilder` method has `useSimpleConsoleLogger` parameter, but `UseBatchEngine` and `RunBatchEngineAsync` methods also have `useSimpleConsoleLogger`.
If I want to disable SimpleConsoleLogger, I need to write `useSimpleConsoleLogger` in two places.
Considering consistency, I think that it is better not to add any logger in BatchEngine initialization process.
=> Remove SimpleConsoleLogger dependency from BatchEngine initialization.

.circleci/config.yml, ReadMe.md, sandbox/MultiContainedApp/MultiContainedApp.csproj, sandbox/SingleContainedApp/SingleContainedApp.csproj, sandbox/SingleContainedAppWithConfig/SingleContainedAppWithConfig.csproj, sandbox/WebHostingApp/WebHostingApp.csproj, src/MicroBatchFramework.WebHosting/BatchEngineSwaggerMiddleware.cs, src/MicroBatchFramework.WebHosting/MicroBatchFramework.WebHosting.csproj, src/MicroBatchFramework/BatchHost.cs, src/MicroBatchFramework/MicroBatchFramework.csproj, tests/MicroBatchFramework.Tests/MicroBatchFramework.Tests.csproj
Upgrade Microsoft.Extensions.Hosting to 3.0.0 and .NET Core to 3.0.
- MicroBatchFramework is still using .NET Standard 2.0
- MicroBatchFramework.WebHosting is now using ASP.NET Core 3.0
Microsoft.Extensions.Hosting 3.0.0 provides pre-configured generic `Host` class and its host builder. This PR makes MicroBatchFramework use `Host.CreateDefaultBuilder`.
=> Upgrade Microsoft.Extensions.Hosting and .NET Core

ReadMe.md, src/MicroBatchFramework/BatchEngine.cs, tests/MicroBatchFramework.Tests/AssemblyInfo.cs, tests/MicroBatchFramework.Tests/ExitCodeTest.cs
In some use cases, an application is expected to return `0`/`1` or other exit code.
This PR implements the ability to return the user-specified exit code.
- ref: #17 - Proposal: New API to return Exit Code
=> Treat the return value as the exit code.

sandbox/SingleContainedAppWithConfig/Program.cs, src/MicroBatchFramework/BatchEngineService.cs
Fix #21 
When the app is running in the `Development` environment, the default ServiceProvider validates about scope usage. (ref: [Scope Validation - Dependency Injection in ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0#scope-validation))
This PR changes `BatchEngineService` to create scope at the start, so that provides the scoped services properly.
> **NOTE**: In BatchEngineService, `Scoped` service is almost same as `Singleton` service.
=> Create scope service while BatchEngineService is starting.

src/MicroBatchFramework/BatchHost.cs, src/MicroBatchFramework/SimpleConsoleLogger.cs
Microsoft.Extensions.Logging's log filter selects **one** filter rule at once.
If multiple rules are matched, take the last one. The library should not depend on this behavior.
```csharp
logger
.AddFilter((providerName, category, logLevel) =>
{
Console.WriteLine("AddFilter#1");
return false;
})
.AddFilter((providerName, category, logLevel) =>
{
Console.WriteLine("AddFilter#2");
return false;
})
.AddFilter((providerName, category, logLevel) =>
{
// On runtime, a logger uses this filter rule only.
Console.WriteLine("AddFilter#3");
return false;
})
```
=> Remove the logger filter registration.

src/MicroBatchFramework/BatchEngine.cs
https://github.com/Cysharp/MicroBatchFramework/blob/6ddb766e20c5779d7b74b60012171d489df8eee9/src/MicroBatchFramework/BatchEngine.cs#L332
上記のOrderByで、xとyが一致するのにCustomSorterが1や-1を返すとソートが停止しない実装があるようです。以下のようなコマンドを定義した際、.NET Core3では止まりましたが、.NET Framwork 4.7.2で停止しませんでした。
```cs
public void Default() {}
[Command("last", "hoge")]
public void Last() {}
[Command("all", "piyo")]
public void All() {}
```
=> CustomSorter should return 0 when x equals y

src/MicroBatchFramework.WebHosting/BatchEngineHostingExtensions.cs, src/MicroBatchFramework.WebHosting/BatchEngineMiddleware.cs, src/MicroBatchFramework.WebHosting/MicroBatchFramework.WebHosting.csproj, src/MicroBatchFramework.WebHosting/Swagger/Schemas/SwaggerDocument.cs, src/MicroBatchFramework.WebHosting/Swagger/SwaggerDefinitionBuilder.cs, src/MicroBatchFramework.WebHosting/Swagger/SwaggerOptions.cs, src/MicroBatchFramework/BatchBase.cs, src/MicroBatchFramework/BatchContext.cs, src/MicroBatchFramework/BatchEngine.cs, src/MicroBatchFramework/BatchEngineHostBuilderExtensions.cs, src/MicroBatchFramework/BatchEngineService.cs, src/MicroBatchFramework/CommandAttribute.cs, src/MicroBatchFramework/CompositeBatchInterceptor.cs, src/MicroBatchFramework/IBatchInterceptor.cs, src/MicroBatchFramework/MicroBatchFramework.csproj, src/MicroBatchFramework/OptionAttribute.cs
- set Nullable to `enable`
- fix warnings caused by NRT
This PR will be **BREAKING** change if this library is used in a `nullable` context.
It causes *only* warnings on some inappropriate code, but .NET has "treat warnings as errors" option. 
```csharp
using MicroBatchFramework;
public class BatchSample : BatchBase
{
#nullable disable
public void NoWarnCommand()
{
this.Context = null;  // No Warn
}
#nullable restore
#nullable enable
public void WarnCommand()
{
this.Context = null;  // Cause warning CS8625
}
#nullable restore
}
```
=> Enable Nullable Reference Type(annotations)

ReadMe.md, sandbox/SingleContainedApp/Program.cs, src/MicroBatchFramework.WebHosting/BatchEngineHostingExtensions.cs, src/MicroBatchFramework.WebHosting/MicroBatchFramework.WebHosting.csproj, src/MicroBatchFramework.WebHosting/Swagger/Schemas/SwaggerDocument.cs, src/MicroBatchFramework.WebHosting/Swagger/SwaggerDefinitionBuilder.cs, src/MicroBatchFramework/BatchEngine.cs, src/MicroBatchFramework/EmptyHostedService.cs, src/MicroBatchFramework/MicroBatchFramework.csproj, tests/MicroBatchFramework.Tests/MicroBatchFramework.Tests.csproj
* using `System.Text.Json` instead of `Utf8Json`, `Newtonsoft.Json`.
* Array argument handling more friendly. (e.g. `int[]` can handle by `1 2 3`, `string[]` can handle by `foo bar baz`).
=> Improve array handling, remove Utf8Json dependency

.github/workflows/stale.yml
close no update, comment issue & pr.
please make `wip` and `stale` label.
* schedule: run 1 time for a day.
* enable issue: true
* enable pr: true
* when: 90 day no update.
* close: past 7 day after stale mark
* ignore execution on label: `wip`
* reset stale when update: true
=> chore: stale issue & pr not update

src/ConsoleAppFramework.WebHosting/ConsoleAppFramework.WebHosting.csproj, src/ConsoleAppFramework/ConsoleAppFramework.csproj, tests/ConsoleAppFramework.Tests/ConsoleAppFramework.Tests.csproj
Microsoft.Extentions.* 3.1.0 has issue when `dotnet pack`.
> Error Message: "The DateTimeOffset specified cannot be converted into a Zip file timestamp"
This PR bump up Microsoft.Extentions.* to 3.1.5 and also it's dependencies.
https://github.com/NuGet/Home/issues/7001
=> chore: bump up package Microsoft.Extentions.* to 3.1.5

src/ConsoleAppFramework/CommandHelpBuilder.cs, src/ConsoleAppFramework/ConsoleAppEngine.cs, tests/ConsoleAppFramework.Tests/CommandHelpTest.cs, tests/ConsoleAppFramework.Tests/SingleContainedTest.cs
Fixes #52.
This PR also includes:
* Fix indentation logic which did not assume lack of value type legend.
* Some refactoring which resolves maintenanceability issues found by this PR work.
=> Omit value type legend from boolean option

src/ConsoleAppFramework/CommandHelpBuilder.cs, tests/ConsoleAppFramework.Tests/CommandHelpTest.cs
correct display of command class name help text
=> Hotfix displayhelpcommand

src/ConsoleAppFramework/ConsoleAppFilter.cs, tests/ConsoleAppFramework.Tests/Integration/CommandFilterTest.cs
When `ConsoleAppFilter`-derived filter is applied via attribute, application crashes with following error:
System.InvalidOperationException: A suitable constructor for type 'ConsoleAppFramework.ConsoleAppFilter' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
at ConsoleAppFramework.WithFilterInvoker.InvokeAsync() in …
=> Attaching filter via attribute leads to InvalidOperationException

src/ConsoleAppFramework/ConsoleAppBuilder.cs, src/ConsoleAppFramework/ConsoleAppEngine.cs, src/ConsoleAppFramework/ParamsValidator.cs, tests/ConsoleAppFramework.Tests/Integration/ValidationAttributeTests.cs
Implemented an ability to validate commands' parameters via validation attributes from `System.ComponentModel.DataAnnotations` namespace and custom ones inheriting `ValidationAttribute` type
Example:
```c#
using System.ComponentModel.DataAnnotations;
// ...
/// <inheritdoc />
internal class TestConsoleApp : ConsoleAppBase
{
public const string Output = $"hello from {nameof(TestConsoleApp)}";
[Command(nameof(SomeCommand))]
public void SomeCommand(
[EmailAddress] string firstArg,
[Range(0, 2)]  int secondArg) => Console.WriteLine(Output);
}
```
Output (command invoked with params [**--first-arg "invalid-email-address" --second-arg" 10**])
```
Some parameters have invalid values:
first-arg (invalid-email-address): The String field is not a valid e-mail address.
second-arg (10): The field …
```
=> Parameters validation via attributes

src/ConsoleAppFramework/ConsoleAppEngine.cs, tests/ConsoleAppFramework.Tests/Integration/SingleCommandTest.Arguments.cs
**Sample Application**
I have a console application that takes a DateTime argument as follows: 
```csharp
var app = ConsoleApp.Create(args);
app.AddRootCommand((DateTime dt) =>
{
Console.WriteLine($"dt: {dt}");
});
app.Run();
```
**Current Behavior**
`Example 1`: Enclose parameter value in escaped double quotations.
```ps1
> ConsoleApp.exe --dt '\"2022-07-07\"'
```
This will work correctly, but following `Example 2` will not work.
`Example 2`: Parameter value only (without escaped double quotations).
```ps1
> ConsoleApp.exe --dt "2022-07-07"
```
**New Behavior**
`Example 1`: Enclose parameter value in escaped double quotations.
```ps1
> ConsoleApp.exe --dt '\"2022-07-07\"'
```
This works correctly as before.
`Example 2`: Parameter value only (without escaped double quotations).
We don't …
=> improve parsing of command-line arguments

src/ConsoleAppFramework/ConsoleAppEngine.cs, tests/ConsoleAppFramework.Tests/Integration/SingleCommandTest.Options.cs
When command parameter name is provided without value, engine crashes with error 'Index was outside the bounds of the array' instead of writing informative message to output
Example:
```csharp
public class TestConsoleApp : ConsoleAppBase
{
public void Hello(string name) => Console.WriteLine($"hello {name}");
}
```
If app is executed as "MyApp.exe --name" (value for 'name' is not provided):
```
ConsoleAppFramework.ConsoleApp[0]
Index was outside the bounds of the array. args: --hello --name
```
This PR fixes this small issue
=> error 'Index was outside the bounds of the array'

src/ConsoleAppFramework/CommandHelpBuilder.cs, src/ConsoleAppFramework/ConsoleAppEngine.cs, src/ConsoleAppFramework/ParameterInfoExtensions.cs
For declaring some command like this
`[Command("run", "Run commandlet.")] public async Task RunCommandlet([Option(0)] string commandlet, [Option(1)] params string[] parameters)`
if last indexed parameter is params then it will accept all leftover parameters from command line
For example myprog run CommandletName param1 param2 - param1 param2 will be put to parameters array
In case of myprog run CommandletName - parameters will be empty.
=> Enable (param string[] something) to accept arbitrary number of parameters. 

.github/workflows/build-release.yml
Replace create-release with `Cysharp/Actions/.github/workflows/create-release.yaml`.
This brings central managed release flow control.
see: https://github.com/Cysharp/ConsoleAppFramework/actions/runs/7813660715
=> ci: use Cysharp/Actions/.github/workflows/create-release.yaml

src/ConsoleAppFramework/ConsoleAppGenerator.cs
I've noticed the value printed in `ThrowArgumentParseFailed` may not be correct in some cases, like when `TryIncrementIndex` fails, it will print the argument name itself, rather than the value (because there isn't one). Maybe this should be special cased to a new exception like `Argument '{argumentName}' requires a value, but none was specified.`?
=> Improve grammar of exceptions

src/ConsoleAppFramework/RoslynExtensions.cs
Use correct spelling for `ClassDeclarationSyntax` variable
=> Rename ClassDeclarationSyntax variable from primartyCtor to primaryCtor

src/ConsoleAppFramework/Parser.cs, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppBuilderTest.cs
fix for #134.
The cause of this issue was that we were referencing the first element of the attribute list (GetAttributes()[0]) when retrieving the command name.
Please review the code changes.
=> fix IndexOutOfRangeException when ConsoleAppFilterAttribute is defined above CommandAttribute

src/ConsoleAppFramework/Parser.cs, tests/ConsoleAppFramework.GeneratorTests/HelpTest.cs
Our 
```cs
<param name="param_name">-p, Param description, example: "a,b,c".</param>
```
Was being converted to
```
Param description example: "abc".
```
on the helptext output.
=> Fix commas being stripped from helptext

src/ConsoleAppFramework/ConsoleAppBaseCode.cs
Suppress warning CS1591 on `ConsoleAppFrameworkGeneratorOptionsAttribute`
=> Suppress warning CS1591

tests/ConsoleAppFramework.GeneratorTests/CSharpGeneratorRunner.cs, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppBuilderTest.cs, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppFramework.GeneratorTests.csproj, tests/ConsoleAppFramework.GeneratorTests/GlobalUsings.cs, tests/ConsoleAppFramework.GeneratorTests/IncrementalGeneratorTest.cs, tests/ConsoleAppFramework.GeneratorTests/NameConverterTest.cs, tests/ConsoleAppFramework.GeneratorTests/RunTest.cs
`FluentAssertions` has been acquired and changed to a commercial license.
https://github.com/fluentassertions/fluentassertions/pull/2943
Such an abrupt license change from OSS is unacceptable.
I removed `FluentAssertions` and switched to [Shouldly](https://github.com/shouldly/shouldly), which provides equivalent functionality.
=> Remove FluentAssertions, Use Shouldly

sandbox/CliFrameworkBenchmark/CliFrameworkBenchmark.csproj, sandbox/CliFrameworkBenchmark/Commands/SystemCommandLineCommand.cs, sandbox/CliFrameworkBenchmark/Program.cs, sandbox/CliFrameworkBenchmark/Properties/launchSettings.json
**What's included in this PR**
1. Update `BenchmarkDotNet` package to latest version
2. Update `System.CommandLine` from `beta1` to `beta4`
3. Modify `Program.cs`  and add `launchSettings.json` for measuring **average** cold startup time
**Benchmark results**
>dotnet run -c Release -- --launchCount 20
Method                   | Mean       | Error     | StdDev    | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------------------- |-----------:|----------:|----------:|------:|--------:|----------:|------------:|
| 'ConsoleAppFramework v5' |   1.558 ms | 0.1154 ms | 0.1329 ms |  1.01 |    0.11 |     400 B |        1.00 |
| CliFx                    |  24.850 ms | 0.5209 ms | 0.5999 ms | 16.04 |    1.25 |   57640 B |      144.10 |
| System.CommandLine       |  29.528 ms | 3.3015 ms | …
=> chore: Update benchmarks

src/ConsoleAppFramework/ConsoleAppBaseCode.cs, tests/ConsoleAppFramework.GeneratorTests/CSharpGeneratorRunner.cs
This PR intended to fix part of issue #162.
By ignoring line ending difference with `StringCompareShould.IgnoreLineEndings` option.
Additionally, I've removed extra spaces from source generation code
=> fix: Tests failed when line-end characters differ from OS default

src/ConsoleAppFramework/ConsoleAppGenerator.cs, src/ConsoleAppFramework/StringExtensions.cs
This PR intended to fix issue reported at #162
**What's changed in this PR**
1. Add `ReplaceLineEndings` extension method that normalize line endings.
2. Normalize line endings on outputting generated source code.
=> fix: Normalize line endings of generated source code

ConsoleAppFramework.sln, sandbox/GeneratorSandbox/Program.cs, sandbox/GeneratorSandbox/Properties/launchSettings.json, tests/ConsoleAppFramework.GeneratorTests/ArrayParseTest.cs, tests/ConsoleAppFramework.GeneratorTests/CSharpGeneratorRunner.cs, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppBuilderTest.cs, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppFramework.GeneratorTests.csproj, tests/ConsoleAppFramework.GeneratorTests/DiagnosticsTest.cs, tests/ConsoleAppFramework.GeneratorTests/FilterTest.cs, tests/ConsoleAppFramework.GeneratorTests/HelpTest.cs, tests/ConsoleAppFramework.GeneratorTests/NameConverterTest.cs, tests/ConsoleAppFramework.GeneratorTests/RunTest.cs, tests/ConsoleAppFramework.GeneratorTests/SubCommandTest.cs, tests/Directory.Build.props
This PR intended to update xUnit version to latest v3.
And switch test runner to use  `Microsoft.Testing.Platform` based runner instead of VSTest.
- 1.1. Update following NuGet packages and fix build errors.
- Shouldly
- Microsoft.NET.Test.Sdk
- xunit -> xunit.v3
- xunit.runner.visualstudio
- 1.2. Fix build errors/warnings. 
- 2.1. Add `tests\Directory.Build.props` file and add setting to use `Microsoft.Testing.Platform`
- 2.2. Modify `CSharpGeneratorRunner.cs` and add additional DLL references. 
(It's seems be required when using `xunit.runner.visualstudio` v2.5.0 or later) 
- 2.3. Implement `IDisposable` interface on some class and clear `Environment.ExitCode` on every test run finished. 
- 2.4. Modify assembly version check logics at `HelpTest.cs`
=> Update tests related projects

ReadMe.md, src/ConsoleAppFramework/Command.cs, src/ConsoleAppFramework/CommandHelpBuilder.cs, src/ConsoleAppFramework/ConsoleAppBaseCode.cs, src/ConsoleAppFramework/Parser.cs, tests/ConsoleAppFramework.GeneratorTests/HiddenAttributeTest.cs
This PR intended to fix #142
**HiddenAttribute's behaviors**
1. When  `[Hidden]` attribute is set on command.  It hide command from **command list**.  
It can show hidden command help when  explicitly specify hidden command name with `--help` parameter
2. When [Hidden] attribute is set on command parameter. It hide parameter from command help.
Note: When both `[Argument]`/[Hidden] attribute set. It **silently** ignore `Hidden` attribute.  
(Because it's positional parameter)
=> feat: Add HiddenAttribute to hide specific command/parameter

sandbox/CliFrameworkBenchmark/Benchmark.cs, sandbox/CliFrameworkBenchmark/CliFrameworkBenchmark.csproj, sandbox/CliFrameworkBenchmark/Commands/SystemCommandLineCommand.cs, sandbox/CliFrameworkBenchmark/Program.cs, sandbox/GeneratorSandbox/GeneratorSandbox.csproj, src/ConsoleAppFramework/ConsoleAppFramework.csproj, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppFramework.GeneratorTests.csproj
This PR update package dependencies and update benchmark relating code.
to test System.CommandLine `2.0.0-beta5`.
**Before this PR merged**
| Method                   | Mean       | Error     | StdDev    | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------------------- |-----------:|----------:|----------:|------:|--------:|----------:|------------:|
| 'ConsoleAppFramework v5' |   1.731 ms | 0.1185 ms | 0.1365 ms |  1.01 |    0.11 |     400 B |        1.00 |
| CliFx                    |  26.083 ms | 0.4402 ms | 0.5069 ms | 15.15 |    1.13 |   62000 B |      155.00 |
| System.CommandLine       |  32.463 ms | 3.0543 ms | 3.5173 ms | 18.86 |    2.42 |   18720 B |       46.80 |
| Cocona.Lite              |  49.657 ms | 1.5002 ms | 1.7277 ms | 28.85 |    2.30 |   60072 B |      150.18 | …
=> chore: Update dependencies and benchmark relating code

src/ConsoleAppFramework/Emitter.cs
This allows the service provider wrapper to be asynchronously dispose from the generated `app.RunAsync()` method.
This method already checks if the provided `IServiceProvider` implements `IAsyncDisposable`. 
This ensures `ToConsoleAppBuilder` always correctly disposes too.
=> Implement IAsyncDisposable on CompositeDisposableServiceProvider

sandbox/GeneratorSandbox/GeneratorSandbox.csproj, sandbox/GeneratorSandbox/Program.cs, sandbox/GeneratorSandbox/Properties/launchSettings.json, src/ConsoleAppFramework/ConsoleAppBaseCode.cs, src/ConsoleAppFramework/Emitter.cs
=> Support external CancellationToken

Directory.Build.props, sandbox/CliFrameworkBenchmark/CliFrameworkBenchmark.csproj, sandbox/FilterShareProject/FilterShareProject.csproj, sandbox/GeneratorSandbox/GeneratorSandbox.csproj, sandbox/NativeAot/NativeAot.csproj, src/ConsoleAppFramework.Abstractions/ConsoleAppFramework.Abstractions.csproj, src/ConsoleAppFramework/ConsoleAppFramework.csproj, tests/ConsoleAppFramework.GeneratorTests/ConsoleAppFramework.GeneratorTests.csproj
Change IsPackable from default, implicitly `true`, to explicitly `false`.
This prevent unintended nuget package generation like sandbox, benchmark, and etc....
Side effect:
- nupkg csproj required to specify `<IsPackable>true</IsPackable>`. Previously they are omitted.
- LICENSE.md is now handled by Directory.Build.props
=> chore: Specify IsPackable=false on Directory.Build.props, explicitly true for target packages.

ReadMe.md, tests/ConsoleAppFramework.GeneratorTests/RunTest.cs
While v4->v5 migrating, it wasn’t immediately clear that “short names” should be defined as parameter aliases in the <param> XML doc comment.
=> Clarify relation between "shortName" and parameter aliases to ease migration in ReadMe and RunTest
